name: GiftShop
version: 0.1.0
author: Vostrikov Vitaliy <rasart.pro@gmail.com>
homepage: https://github.com/Rasarts/giftshop/tree/source
description: front-end for shop on bitrix

dependencies:
  browser: any
  sass: any
  
transformers:
  - sass